global_frame: odom
rolling_window: true

update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5

width: 2.0
height: 2.0

cost_scaling_factor: 1.0

plugins:
  - {name: obstacles,                 type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}